version: 2

project_name: gogcli

changelog:
  disable: true

builds:
  - id: gog
    main: ./cmd/gog
    binary: gog
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - windows_amd64
  - id: gog_darwin
    main: ./cmd/gog
    binary: gog
    env:
      - CGO_ENABLED=1
    targets:
      - darwin_amd64
      - darwin_arm64

archives:
  - builds:
      - gog
      - gog_darwin
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
